### ISSUE TITLE
nltk module not found error

### ISSUE THREAD

**Issue by asanka1055** [vivekpabani/News-Recommendation-System#1]
When I run the main.py it shows the below error. How can I fix the issue and re-run?

Traceback (most recent call last):
  File "F:/4th yr project/Interim/News-Recommendation-System-master/source_code/main.py", line 21, in <module>
    from document import Document
  File "F:\4th yr project\Interim\News-Recommendation-System-master\source_code\document.py", line 13, in <module>
    from nltk.stem.porter import *
ModuleNotFoundError: No module named 'nltk'

**Comment by vivekpabani** [comment]
Sorry, I didn't get this message earlier. It looks like you need to install nltk library.

**Comment by shavaibhav** [comment]
sir,i can't find the library nltk can you provide some solution or link to install.I installed the library but when running main.py it will giving error.

**Comment by vivekpabani** [comment]
See if this helps:

https://stackoverflow.com/questions/27947414/python-cant-find-module-nltk
